apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    name: webserver-deploy
spec:
  #type: LoadBalancer # --> not working for now...
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: webserver-deploy