apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy
  labels:
    app: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webserver-deploy
  template:
    metadata:
      name: webserver-deploy
      labels:
        name: webserver-deploy
    spec:
      containers:
        - name: webserver
          image: dogan2010/webserver:v2
          ports:
          - containerPort: 80
          env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-admin-password
          envFrom:
          - configMapRef:
              name: servers-configmap